UPOS = {
    # POS tags
    # Universal POS Tags
    # http://universaldependencies.org/u/pos/
    "ADJ": "adjective",
    "ADP": "adposition",
    "ADV": "adverb",
    "AUX": "auxiliary",
    "CONJ": "conjunction",
    "CCONJ": "coordinating conjunction",
    "DET": "determiner",
    "INTJ": "interjection",
    "NOUN": "noun",
    "NUM": "numeral",
    "PART": "particle",
    "PRON": "pronoun",
    "PROPN": "proper noun",
    "PUNCT": "punctuation",
    "SCONJ": "subordinating conjunction",
    "SYM": "symbol",
    "VERB": "verb",
    "X": "other",
    "EOL": "end of line",
    "SPACE": "space",
}

XPOS = {
    # POS tags (English)
    # OntoNotes 5 / Penn Treebank
    # https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html
    ".": "punctuation mark, sentence closer",
    ",": "punctuation mark, comma",
    "-LRB-": "left round bracket",
    "-RRB-": "right round bracket",
    "``": "opening quotation mark",
    '""': "closing quotation mark",
    "''": "closing quotation mark",
    ":": "punctuation mark, colon or ellipsis",
    "$": "symbol, currency",
    "#": "symbol, number sign",
    "AFX": "affix",
    "CC": "conjunction, coordinating",
    "CD": "cardinal number",
    "DT": "determiner",
    "EX": "existential there",
    "FW": "foreign word",
    "HYPH": "punctuation mark, hyphen",
    "IN": "conjunction, subordinating or preposition",
    "JJ": "adjective (English), other noun-modifier (Chinese)",
    "JJR": "adjective, comparative",
    "JJS": "adjective, superlative",
    "LS": "list item marker",
    "MD": "verb, modal auxiliary",
    "NIL": "missing tag",
    "NN": "noun, singular or mass",
    "NNP": "noun, proper singular",
    "NNPS": "noun, proper plural",
    "NNS": "noun, plural",
    "PDT": "predeterminer",
    "POS": "possessive ending",
    "PRP": "pronoun, personal",
    "PRP$": "pronoun, possessive",
    "RB": "adverb",
    "RBR": "adverb, comparative",
    "RBS": "adverb, superlative",
    "RP": "adverb, particle",
    "TO": 'infinitival "to"',
    "UH": "interjection",
    "VB": "verb, base form",
    "VBD": "verb, past tense",
    "VBG": "verb, gerund or present participle",
    "VBN": "verb, past participle",
    "VBP": "verb, non-3rd person singular present",
    "VBZ": "verb, 3rd person singular present",
    "WDT": "wh-determiner",
    "WP": "wh-pronoun, personal",
    "WP$": "wh-pronoun, possessive",
    "WRB": "wh-adverb",
    "SP": "space (English), sentence-final particle (Chinese)",
    "ADD": "email",
    "NFP": "superfluous punctuation",
    "GW": "additional word in multi-word expression",
    "XX": "unknown",
    "BES": 'auxiliary "be"',
    "HVS": 'forms of "have"',
    "_SP": "whitespace",
}

POS = {**UPOS, **XPOS}

DEPENDENCIES = {
    "ACL": "Clausal modifier of noun",
    "ACOMP": "Adjectival complement",
    "ADVCL": "Adverbial clause modifier",
    "ADVMOD": "Adverbial modifier",
    "AGENT": "Agent",
    "AMOD": "Adjectival modifier",
    "APPOS": "Appositional modifier",
    "ATTR": "Attribute",
    "AUX": "Auxiliary",
    "AUXPASS": "Auxiliary (passive)",
    "CASE": "Case marker",
    "CC": "Coordinating conjunction",
    "CCOMP": "Clausal complement",
    "COMPOUND": "Compound modifier",
    "CONJ": "Conjunct",
    "CSUBJ": "Clausal subject",
    "CSUBJPASS": "Clausal subject (passive)",
    "DATIVE": "Dative",
    "DEP": "Unclassified dependent",
    "DET": "Determiner",
    "DOBJ": "Direct Object",
    "EXPL": "Expletive",
    "INTJ": "Interjection",
    "MARK": "Marker",
    "META": "Meta modifier",
    "NEG": "Negation modifier",
    "NMOD": "Modifier of nominal",
    "NPADVMOD": "Noun phrase as adverbial modifier",
    "NSUBJ": "Nominal subject",
    "NSUBJPASS": "Nominal subject (passive)",
    "NUMMOD": "Number modifier",
    "OPRD": "Object predicate",
    "PARATAXIS": "Parataxis",
    "PCOMP": "Complement of preposition",
    "POBJ": "Object of preposition",
    "POSS": "Possession modifier",
    "PRECONJ": "Pre-correlative conjunction",
    "PREDET": "Pre-determiner",
    "PREP": "Prepositional modifier",
    "PRT": "Particle",
    "PUNCT": "Punctuation",
    "QUANTMOD": "Modifier of quantifier",
    "RELCL": "Relative clause modifier",
    "ROOT": "Root",
    "XCOMP": "Open clausal complement",
}

CONSTITUENTS = {
    "ADJP": "Adjective Phrase",
    "ADVP": "Adverb Phrase",
    "CONJP": "Conjunction Phrase",
    "FRAG": "Fragment",
    "INTJ": "Interjection",
    "LST": "List Marker",
    "NAC": "Not A Constituent (used to mark parts of a sentence that cannot be considered as a single constituent)",
    "NML": "Noun Phrase as a modifier of another noun",
    "NP": "Noun Phrase",
    "PP": "Prepositional Phrase",
    "PRN": "Parenthetical",
    "PRT": "Particle",
    "QP": "Quantifier Phrase",
    "ROOT": "The root of the sentence, typically representing the main clause",
    "RRC": "Reduced Relative Clause",
    "S": "Sentence",
    "SBAR": "Subordinating Clause",
    "SBARQ": "Direct Question Introduced by a Wh-element",
    "SINV": "Inverted Declarative Sentence",
    "SQ": "Inverted Yes/No Question",
    "UCP": "Unlike Coordinated Phrase",
    "VP": "Verb Phrase",
    "WHADJP": "Wh-adjective Phrase",
    "WHADVP": "Wh-adverb Phrase",
    "WHNP": "Wh-noun Phrase",
    "WHPP": "Wh-prepositional Phrase",
    "X": "Unknown or Unanalyzed Constituent",
}


CP_LABELS = {**POS, **CONSTITUENTS}

AMR_LABELS_PAWS_TRAIN = [
    ":ARG3",
    ":prep-among",
    ":prep-on-behalf-of",
    ":example-of",
    ":prep-in",
    ":domain-of",
    ":season",
    ":poss-of",
    ":polite",
    ":prep-under",
    ":year2",
    ":beneficiary",
    ":ARG1-of",
    ":concession-of",
    ":instrument-of",
    ":prep-from",
    ":year",
    ":polarity",
    ":prep-for",
    ":quant",
    ":op1",
    ":value",
    ":ord-of",
    ":degree-of",
    ":month",
    ":prep-against",
    ":unit",
    ":century",
    ":frequency",
    ":op10",
    ":calendar",
    ":op1-of",
    ":duration",
    ":age",
    ":prep-per",
    ":example",
    ":ARG0-of",
    ":decade",
    ":op13",
    ":dayperiod",
    ":prep-with",
    ":quant-of",
    ":snt2",
    ":part",
    ":prep-along-with",
    ":op6",
    ":direction",
    ":concession",
    ":prep-without",
    ":topic-of",
    ":topic",
    ":path-of",
    ":snt1",
    ":polarity-of",
    ":ARG2-of",
    ":medium",
    ":prep-by",
    ":op9",
    ":ARG7",
    ":degree",
    ":instrument",
    ":poss",
    ":name",
    ":location",
    ":part-of",
    ":accompanier",
    ":ARG3-of",
    ":location-of",
    ":ARG5",
    ":consist-of",
    ":op8",
    ":subevent",
    ":age-of",
    ":prep-to",
    ":ARG6",
    ":subevent-of",
    ":source-of",
    ":op7",
    ":era",
    ":snt3",
    ":mod",
    ":year15",
    ":op3",
    ":direction-of",
    ":quarter",
    ":duration-of",
    ":prep-into",
    ":op2",
    ":extent",
    ":ARG0",
    ":condition",
    ":op3-of",
    ":time-of",
    ":li",
    ":weekday",
    ":ARG2",
    ":destination",
    ":purpose",
    ":ARG8",
    ":day",
    ":op12",
    ":ARG6-of",
    ":mode",
    ":path",
    ":op5",
    ":ARG4",
    ":mod-of",
    ":prep-as",
    ":time",
    ":consist",
    ":op4",
    ":timezone",
    ":range",
    ":prep-at",
    ":prep-on",
    ":manner-of",
    ":op11",
    ":scale",
    ":source",
    ":ARG4-of",
    ":ord",
    ":domain",
    ":match-03",
    ":accompanier-of",
    ":op4-of",
    ":manner",
    ":ARG1",
    ":op2-of",
    ":medium-of",
    ":prep-up-to",
]

AMR_LABELS_QQP_TRAIN = [
    ":ARG5",
    ":ARG4-of",
    ":accompanier",
    ":purpose-of",
    ":ren",
    ":temporally",
    ":unit",
    ":subevent",
    ":poss",
    ":manner",
    ":prep-against-of",
    ":against",
    ":duration",
    ":concession",
    ":prep-as",
    ":prep-on-behalf-of",
    ":degree",
    ":ARG3",
    ":snt3",
    ":degree-of",
    ":polarity-of",
    ":location",
    ":beneficiary",
    ":prep-in-of",
    ":subevent-of",
    ":ord",
    ":beneficiary-of",
    ":instrument-of",
    ":prep-along-with",
    ":consist",
    ":season",
    ":prep-without",
    ":op7",
    ":polarity",
    ":prep-among",
    ":op1-of",
    ":acid",
    ":poss-of",
    ":direction-of",
    ":prep-under",
    ":era",
    ":example",
    ":frequency",
    ":prep-to",
    ":snt1",
    ":weekday",
    ":op8",
    ":timezone-of",
    ":prep-for",
    ":concession-of",
    ":mod-of",
    ":part-of",
    ":quant",
    ":ARG2",
    ":polite",
    ":prep-on",
    ":snt4",
    ":century",
    ":source",
    ":decade",
    ":part",
    ":ARG1-of",
    ":op2",
    ":year2",
    ":manchurian",
    ":op6",
    ":condition-of",
    ":ARG2-of",
    ":domain",
    ":dayperiod",
    ":snt3-of",
    ":ARG1",
    ":ARG0",
    ":topic",
    ":quant-of",
    ":value",
    ":prep-at",
    ":prep-against",
    ":medium-of",
    ":scale",
    ":prep-through",
    ":source-of",
    ":age-of",
    ":example-of",
    ":ARG6",
    ":path",
    ":domain-of",
    ":age",
    ":op1",
    ":Homecoming",
    ":duration-of",
    ":frequency-of",
    ":extent",
    ":value-of",
    ":quant775",
    ":manner-of",
    ":P",
    ":prep-into",
    ":snt2",
    ":name",
    ":ord-of",
    ":ARG0-of",
    ":destination",
    ":direction",
    ":consist-of",
    ":prep-with",
    ":instrument",
    ":month",
    ":snt2-of",
    ":ARG4",
    ":prep-in",
    ":medium",
    ":location-of",
    ":op5",
    ":oxide",
    ":topic-of",
    ":op4",
    ":ARG6-of",
    ":range",
    ":ARG5-of",
    ":accompanier-of",
    ":conj-as-if",
    ":extent-of",
    ":day",
    ":op2-of",
    ":path-of",
    ":mod",
    ":op3",
    ":purpose",
    ":year",
    ":time-of",
    ":mode",
    ":op9",
    ":timezone",
    ":condition",
    ":calendar",
    ":D",
    ":ARG3-of",
    ":op3-of",
    ":li",
    ":time",
    ":prep-from",
    ":prep-by",
]

AMR_LABELS_PARANMT_TRAIN = [
    ":prep-at",
    ":quant321",
    ":ARG6",
    ":range",
    ":op10",
    ":ARG01",
    ":ARG10",
    ":prep-against-of",
    ":op39",
    ":ARG1-91",
    ":ARG619",
    ":consist-of",
    ":conj-as-if",
    ":weekday",
    ":with",
    ":subevent",
    ":karumar",
    ":polarity",
    ":prep-against",
    ":direction-of",
    ":beneficiary-of",
    ":prep-up",
    ":prep-in-addition-to",
    ":prep-a",
    ":ARG6-of",
    ":bean",
    ":op6",
    ":medium-of",
    ":op25",
    ":domain",
    ":prep-as-well",
    ":op17",
    ":accompanier",
    ":negro",
    ":ARG3",
    ":li456",
    ":op1-of",
    ":year",
    ":quant740",
    ":ARG0rome",
    ":calendar",
    ":prep-by",
    ":porenn",
    ":value-of",
    ":prep-per",
    ":op19",
    ":source-of",
    ":ARG0",
    ":clue",
    ":day",
    ":there",
    ":op1",
    ":prep-as",
    ":op22",
    ":prep-without",
    ":ARG7",
    ":extent-of",
    ":beneficiary",
    ":prep-vis-to",
    ":saya",
    ":prep-on-behalf-of",
    ":instrument-of",
    ":ARG5-of",
    ":00",
    ":snt6",
    ":sir",
    ":op11",
    ":op21",
    ":prep-across",
    ":part",
    ":time-of",
    ":quant-of",
    ":li555",
    ":age",
    ":quant605",
    ":op30",
    ":op31",
    ":purpose-of",
    ":acid",
    ":right-06",
    ":prep-in",
    ":snt3-of",
    ":under",
    ":snt9",
    ":name-of",
    ":scale-of",
    ":pak",
    ":domainamy",
    ":patsourakas",
    ":saki",
    ":ARG5",
    ":ord-of",
    ":medium",
    ":mod-of",
    ":sarah",
    ":dearest",
    ":li",
    ":topic-of",
    ":timezone-of",
    ":ARG3-of",
    ":op23",
    ":day-by-day",
    ":sfidi",
    ":prep-toward",
    ":prep-sa",
    ":heft-01",
    ":ARG",
    ":mod321",
    ":concession",
    ":op8",
    ":source",
    ":ARG1",
    ":paddock",
    ":dayperiod",
    ":manner",
    ":time",
    ":op1.op2",
    ":sigh-01",
    ":op15",
    ":pica",
    ":value",
    ":sire",
    ":puke-01",
    ":ARG0rosin",
    ":inhalate-01_1",
    ":prep-on",
    ":ARG2-of",
    ":inhalate-01_2",
    ":direction",
    ":prep-to",
    ":example-of",
    ":prep-among",
    ":mod",
    ":op7",
    ":li415",
    ":age-of",
    ":century",
    ":li-of",
    ":pajama",
    ":op12",
    ":inhalate-01_0",
    ":op6-of",
    ":snt5",
    ":op40",
    ":mod272",
    ":manner-of",
    ":condition",
    ":op16",
    ":mode",
    ":scale",
    ":polarity-of",
    ":era",
    ":op27",
    ":quant626",
    ":duration-of",
    ":ARG1-of",
    ":snt4",
    ":destination-of",
    ":op4",
    ":poss",
    ":polite",
    ":pate",
    ":part-of",
    ":prep-upon",
    ":op9",
    ":quarter",
    ":prep-af",
    ":pidge",
    ":degree-of",
    ":op26",
    ":ARG4",
    ":ARG0-of",
    ":ARG0aristocrat",
    ":purpose",
    ":prep-under",
    ":accompanier-of",
    ":location",
    ":topic",
    ":poss-of",
    ":op24",
    ":op28",
    ":prep-with",
    ":timezone",
    ":month",
    ":location-of",
    ":prep-for",
    ":prep-up-to",
    ":snt1",
    ":purpose-01",
    ":prep-amid",
    ":duration",
    ":snt2-of",
    ":ARG8",
    ":down-01",
    ":possarist",
    ":prep-dari",
    ":aah",
    ":ARG2307",
    ":season",
    ":unit",
    ":path",
    ":consist",
    ":ARG0phantom",
    ":quant",
    ":snt2",
    ":prep-on-of",
    ":prep-in-among",
    ":snt7",
    ":daylight",
    ":up-to",
    ":prep-of",
    ":subevent-of",
    ":ground",
    ":paul",
    ":prep-par",
    ":frequency-of",
    ":path-of",
    ":szarvas",
    ":year2",
    ":op2",
    ":sherlock",
    ":op14",
    ":name",
    ":prep-from",
    ":op38",
    ":prep-",
    ":prep-along-with",
    ":concession-of",
    ":ord",
    ":instrument",
    ":sarge",
    ":destination",
    ":pattie",
    ":condition-of",
    ":decade",
    ":perez",
    ":inhalate-01_3",
    ":oxide",
    ":op4-of",
    ":ARG9",
    ":op5-of",
    ":ARG4-of",
    ":extent",
    ":mod391",
    ":op5",
    ":dayperiod-of",
    ":op13",
    ":op20",
    ":snt8",
    ":example",
    ":domain-of",
    ":suit",
    ":sokka",
    ":ARGwave",
    ":degree",
    ":op3",
    ":ARG0paiute",
    ":op2-of",
    ":op3-of",
    ":frequency",
    ":ARG2",
    ":snt3",
    ":opnow",
    ":ARG0specimen",
    ":quant623",
    ":op18",
    ":prep-into",
]
